name: Update doc-detective-common version

on:
  repository_dispatch:
    types:
      - update-common-package-event
  workflow_dispatch:
    inputs:
      version:
        description: 'The doc-detective-common version.'
        required: false
        default: 'latest'

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install specific version of doc-detective-common
      run: |
        npm install doc-detective-common@${{ github.event.client_payload.version || github.event.inputs.version }}
    
    - name: Test the installation
      run: |
        npm install
        npm test
    
    - name: Commit changes
      run: |
        git add package.json package-lock.json
        git commit -m "chore: bump doc-detective-common version to ${{ github.event.client_payload.version || github.event.inputs.version }}"
